language: go

go:
  - 1.8

install:
  - go get github.com/fatih/color
  - go get github.com/google/go-github/github
  - go get golang.org/x/oauth2
  - go get github.com/google/subcommands

script:
  - go test $(go list ./... | grep -v /vendor/)
