language: go

go:
  - 1.8
install:
  - go get github.com/fatih/color
  - go get github.com/google/go-github/github
  - go get golang.org/x/oauth2
  - go get github.com/google/subcommands
# before_script:
#   - psql --version
#   - sh -c "if [ '$ORM_DRIVER' = 'postgres' ]; then psql -c 'create database orm_test;' -U postgres; fi"
#   - sh -c "if [ '$ORM_DRIVER' = 'mysql' ]; then mysql -u root -e 'create database orm_test;'; fi"
#   - sh -c "if [ '$ORM_DRIVER' = 'sqlite' ]; then touch $TRAVIS_BUILD_DIR/orm_test.db; fi"
#   - sh -c "if [ $(go version) == *1.[5-9]* ]; then go get github.com/golang/lint/golint; golint ./...; fi"
#   - sh -c "if [ $(go version) == *1.[5-9]* ]; then go tool vet .; fi"
#   - mkdir -p res/var
#   - ./ssdb/ssdb-server ./ssdb/ssdb.conf -d
# after_script:
#   -killall -w ssdb-server
#   - rm -rf ./res/var/*
script:
  - go build
# addons:
  # postgresql: "9.4"